"""
src/report_export.py

Generates downloadable DOCX and PDF reports from an analyze_paper() result.

IMPORTANT — Bengali rendering:
DOCX rendering (Word/LibreOffice/Pages) uses a real text-shaping engine, so Bengali
conjuncts/matras render correctly as long as a Bengali-capable font is installed and
declared. PDF is generated by converting that DOCX through LibreOffice (not drawn
directly), because direct PDF-drawing libraries like reportlab do NOT perform complex
script shaping — they map one Unicode codepoint to one glyph, which breaks Bengali.

Setup required on this machine:
1. Install the bundled font "NotoSansBengali.ttf" (double-click -> Install Font on macOS)
   so DOCX viewers can render Bengali correctly.
2. Install LibreOffice for PDF export: `brew install --cask libreoffice`
   (provides the `soffice` command used to convert DOCX -> PDF with correct shaping)
"""

import io
import os
import shutil
import subprocess
import tempfile

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn


ACCENT_COLOR_DOCX = RGBColor(0x1F, 0x4E, 0x5F)  # deep teal

# Any font name here works as long as it's installed on this machine and covers
# both Latin and Bengali script. Noto Sans Bengali (bundled) covers both.
BODY_FONT = "Noto Sans Bengali"


def _set_run_font(run, font_name=BODY_FONT):
    """
    Set the font for ALL script categories on a run (ascii, high-ansi, east asian,
    and — critically for Bengali/Devanagari/etc — complex script "cs"). Without the
    "cs" attribute, Word/LibreOffice may pick a different fallback for non-Latin text
    even if you set .font.name, which only touches the ascii/hAnsi slots.
    """
    run.font.name = font_name
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = rPr.makeelement(qn("w:rFonts"), {})
        rPr.append(rFonts)
    for attr in ("w:ascii", "w:hAnsi", "w:eastAsia", "w:cs"):
        rFonts.set(qn(attr), font_name)


def _build_sections(analysis: dict):
    return [
        ("Key Points", "list", analysis.get("key_points", [])),
        ("Novelty", "para", analysis.get("novelty", "")),
        ("Research Gap", "para", analysis.get("research_gap", "")),
        ("Future Work", "para", analysis.get("future_work", "")),
        ("Conclusion Summary", "para", analysis.get("conclusion_summary", "")),
        ("Core Technologies", "tags", analysis.get("core_tech_tags", [])),
    ]


def generate_docx_report(analysis: dict, paper_title: str = "Research Paper Analysis") -> io.BytesIO:
    doc = Document()

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title_run = title_p.add_run(paper_title)
    title_run.font.size = Pt(20)
    title_run.font.bold = True
    title_run.font.color.rgb = ACCENT_COLOR_DOCX
    _set_run_font(title_run)

    subtitle_p = doc.add_paragraph()
    sub_run = subtitle_p.add_run("AI-Generated Analysis — GyanGrid AI")
    sub_run.font.size = Pt(11)
    sub_run.font.italic = True
    sub_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    _set_run_font(sub_run)

    doc.add_paragraph()

    for heading, kind, content in _build_sections(analysis):
        h = doc.add_heading(level=2)
        h_run = h.add_run(heading)
        h_run.font.color.rgb = ACCENT_COLOR_DOCX
        h_run.font.size = Pt(14)
        _set_run_font(h_run)

        if kind == "list":
            items = content if content else ["Not available."]
            for item in items:
                p = doc.add_paragraph(style="List Bullet")
                r = p.add_run(item)
                _set_run_font(r)
        elif kind == "tags":
            p = doc.add_paragraph()
            r = p.add_run(", ".join(content) if content else "Not available.")
            _set_run_font(r)
        else:
            p = doc.add_paragraph()
            r = p.add_run(content if content else "Not available.")
            _set_run_font(r)

        doc.add_paragraph()

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def _find_soffice() -> str:
    """Locate the LibreOffice `soffice` binary across common install locations."""
    candidates = [
        "/Applications/LibreOffice.app/Contents/MacOS/soffice",  # macOS default
        "/opt/homebrew/bin/soffice",  # Apple Silicon Homebrew symlink
        "/usr/local/bin/soffice",     # Intel Homebrew symlink
        "/usr/bin/soffice",           # Linux
        shutil.which("soffice"),      # anything on PATH
    ]
    for path in candidates:
        if path and os.path.exists(path):
            return path
    raise EnvironmentError(
        "LibreOffice (soffice) not found. Install it with:\n"
        "    brew install --cask libreoffice\n"
        "PDF export converts the generated DOCX through LibreOffice so that "
        "Bengali text shapes correctly — this is required for PDF export to work."
    )


def generate_pdf_report(analysis: dict, paper_title: str = "Research Paper Analysis") -> io.BytesIO:
    """
    Builds the DOCX report, then converts it to PDF via LibreOffice.

    Key design decisions:
    - Uses --norestore to prevent LibreOffice from trying to restore a previous session.
    - Uses a fresh --user-installation dir (isolated per call) so this headless call
      never conflicts with a LibreOffice instance the user already has open on their Mac.
      Without isolation, LibreOffice silently fails with no error output when its profile
      is locked by a running GUI instance.
    - Direct PDF drawing (e.g. reportlab) is intentionally NOT used because reportlab
      has no complex-script shaping engine — Bengali conjuncts/matras break.
    """
    soffice_path = _find_soffice()
    docx_buffer = generate_docx_report(analysis, paper_title)

    with tempfile.TemporaryDirectory() as tmpdir:
        # Write the DOCX to a temp file
        docx_path = os.path.join(tmpdir, "report.docx")
        with open(docx_path, "wb") as f:
            f.write(docx_buffer.read())

        # Isolated user profile dir — avoids lock conflicts with any open LO instance
        lo_profile_dir = os.path.join(tmpdir, "lo_profile")
        os.makedirs(lo_profile_dir, exist_ok=True)
        user_installation = f"file://{lo_profile_dir}"

        result = subprocess.run(
            [
                soffice_path,
                f"-env:UserInstallation={user_installation}",
                "--headless",
                "--norestore",
                "--convert-to", "pdf",
                "--outdir", tmpdir,
                docx_path,
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )

        pdf_path = os.path.join(tmpdir, "report.pdf")

        if not os.path.exists(pdf_path):
            raise RuntimeError(
                f"PDF was not created.\n"
                f"soffice path: {soffice_path}\n"
                f"Return code: {result.returncode}\n"
                f"stdout: {result.stdout}\n"
                f"stderr: {result.stderr}"
            )

        with open(pdf_path, "rb") as f:
            pdf_bytes = f.read()

    buffer = io.BytesIO(pdf_bytes)
    buffer.seek(0)
    return buffer


if __name__ == "__main__":
    sample_analysis_bn = {
        "key_points": [
            "বাংলাদেশের মাধ্যমিক শিক্ষার্থীদের জন্য একটি নতুন ডেটাসেট তৈরি করা হয়েছে।",
            "প্রতিটি প্রশ্নের সাথে ধাপে ধাপে ইঙ্গিত যুক্ত করা হয়েছে।",
        ],
        "novelty": "এই গবেষণায় প্রথমবারের মতো একটি সম্পূর্ণ কনটেক্সচুয়াল বাংলা ডেটাসেট উপস্থাপন করা হয়েছে।",
        "research_gap": "বাংলা ভাষায় শিক্ষামূলক ডেটাসেটের অভাব রয়েছে।",
        "future_work": "ভবিষ্যতে আরও বিষয় অন্তর্ভুক্ত করে ডেটাসেট সম্প্রসারণ করা হবে।",
        "conclusion_summary": "এই গবেষণাটি বাংলা ভাষার শিক্ষাক্ষেত্রে একটি গুরুত্বপূর্ণ পদক্ষেপ।",
        "core_tech_tags": ["NLP", "Bangla", "RAG", "TigerLLM"],
    }
    with open("test_report_bn.docx", "wb") as f:
        f.write(generate_docx_report(sample_analysis_bn, "নমুনা গবেষণাপত্র").read())
    print("Wrote test_report_bn.docx")

    try:
        with open("test_report_bn.pdf", "wb") as f:
            f.write(generate_pdf_report(sample_analysis_bn, "নমুনা গবেষণাপত্র").read())
        print("Wrote test_report_bn.pdf")
    except EnvironmentError as e:
        print(f"Skipped PDF test: {e}")